In [5]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("messy_customer_data.csv")

In [10]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [11]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 10000
Number of columns: 12

In [12]:
df.columns

Index(['CustomerID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_purchase_date', 'purchase_amount', 'feedback_score', 'email',
       'Phone_number', 'Country'],
      dtype='str')

In [13]:
df.dtypes

CustomerID                str
Name                      str
Gender                    str
Age                   float64
City                      str
Signup_Date               str
Last_purchase_date        str
purchase_amount       float64
feedback_score        float64
email                     str
Phone_number              str
Country                   str
dtype: object

In [14]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.describe(include="all")

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
count,7621,8342,7545,7424.000000,8870,7471,6714,4967.000000,7538.000000,4934,7556,8296
unique,7621,10,6,NaN,8,1842,1630,NaN,NaN,4934,2512,5
top,C2,Rahul,Male,NaN,Hyderabad,not_a_date,missing,NaN,NaN,user1mail.com,abc123,USA
freq,1,876,1325,NaN,1144,2475,3366,NaN,NaN,1,2586,1679
mean,NaN,NaN,NaN,78.904364,NaN,NaN,NaN,713.654008,4.008092,NaN,NaN,NaN
std,NaN,NaN,NaN,87.817619,NaN,NaN,NaN,2002.187228,4.619336,NaN,NaN,NaN
min,NaN,NaN,NaN,-5.000000,NaN,NaN,NaN,-999.000000,-1.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,-5.000000,NaN,NaN,NaN,-999.000000,-1.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,43.000000,NaN,NaN,NaN,-999.000000,3.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,200.000000,NaN,NaN,NaN,2437.600000,10.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,200.000000,NaN,NaN,NaN,4998.670000,10.000000,NaN,NaN,NaN

In [1]:
df.isnull().sum()

NameError: name 'df' is not defined

In [2]:
import pandas as pd

In [3]:
import pandas as pd

In [4]:
df.head()

NameError: name 'df' is not defined

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("messy_customer_data.csv")

In [7]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [8]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           2529
Last_purchase_date    3286
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [9]:
import numpy as np

df = df.replace(["missing", "not_a_date", ""], np.nan)

In [10]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           5004
Last_purchase_date    6652
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          7621 non-null   str
 1   Name                8342 non-null   str
 2   Gender              7545 non-null   str
 3   Age                 7424 non-null   float64
 4   City                8870 non-null   str
 5   Signup_Date         4996 non-null   str
 6   Last_purchase_date  3348 non-null   str
 7   purchase_amount     4967 non-null   float64
 8   feedback_score      7538 non-null   float64
 9   email               4934 non-null   str
 10  Phone_number        7556 non-null   str
 11  Country             8296 non-null   str
dtypes: float64(3), str(9)
memory usage: 1.3 MB

In [12]:
df.head()

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.0,2.0,NaN,0,Canada
1,C2,Ravi,Female,NaN,Kolkata,NaN,NaN,NaN,-1.0,user1mail.com,abc123,Canada
2,3,Ravi,female,66.0,Ahmedabad,NaN,20/06/2023,NaN,10.0,user2@mail.com,abc123,India
3,C4,Ankit,male,44.0,Kolkata,NaN,13/09/2025,NaN,NaN,NaN,9316267914,USA
4,5,Rahul,Male,200.0,Ahmedabad,09/07/2025,NaN,-999.0,NaN,user4mail.com,9234603292,USA

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.shape

(10000, 12)

In [15]:
df["CustomerID"].duplicated().sum()

np.int64(2378)

In [16]:
df[df["CustomerID"].duplicated(keep=False)].sort_values("CustomerID").head(20)

,CustomerID,Name,Gender,Age,City,Signup_Date,Last_purchase_date,purchase_amount,feedback_score,email,Phone_number,Country
0,NaN,Ankit,F,36.0,Mumbai,31/12/2024,13/08/2025,-999.00,2.0,NaN,0,Canada
10,NaN,Ankit,NaN,24.0,Chennai,NaN,NaN,NaN,-1.0,user10mail.com,0,NaN
15,NaN,NaN,female,30.0,Pune,NaN,NaN,-999.00,NaN,user15mail.com,abc123,Canada
24,NaN,Ankit,female,NaN,Hyderabad,NaN,NaN,NaN,4.0,NaN,abc123,Australia
26,NaN,Kiran,NaN,NaN,Kolkata,28/05/2024,14/11/2020,4772.57,4.0,user26mail.com,abc123,UK
31,NaN,Rahul,female,200.0,NaN,NaN,09/05/2024,41.61,NaN,NaN,0,Canada
33,NaN,NaN,M,-5.0,Kolkata,16/04/2023,06/04/2023,-999.00,NaN,NaN,9281075045,Canada
41,NaN,Simran,female,NaN,NaN,NaN,NaN,NaN,1.0,user41@mail.com,NaN,Canada
43,NaN,Kiran,Female,50.0,Chennai,13/11/2024,NaN,NaN,-1.0,NaN,0,Australia
45,NaN,Neha,female,67.0,Ahmedabad,NaN,01/07/2022,1661.36,1.0,user45mail.com,0,USA
50,NaN,NaN,F,-5.0,Kolkata,NaN,NaN,NaN,1.0,NaN,abc123,Canada
57,NaN,Pooja,Female,200.0,Chennai,24/09/2023,NaN,-999.00,-1.0,NaN,9208493774,Canada
59,NaN,NaN,male,57.0,Kolkata,NaN,NaN,4812.75,10.0,NaN,0,NaN
61,NaN,NaN,Male,NaN,Kolkata,12/04/2024,21/01/2026,NaN,4.0,NaN,NaN,Australia
73,NaN,Simran,Female,NaN,Bangalore,22/09/2023,18/05/2023,NaN,-1.0,user73@mail.com,NaN,Canada
76,NaN,NaN,NaN,NaN,Bangalore,16/06/2021,NaN,-999.00,2.0,user76@mail.com,9610832582,UK
79,NaN,Ankit,NaN,200.0,Chennai,11/12/2021,NaN,1517.55,1.0,user79@mail.com,abc123,USA
80,NaN,Rahul,Female,NaN,Delhi,NaN,NaN,-999.00,-1.0,NaN,NaN,UK
83,NaN,Priya,Female,NaN,Ahmedabad,NaN,NaN,3720.97,2.0,NaN,abc123,Canada
89,NaN,Ankit,M,51.0,Hyderabad,NaN,NaN,-999.00,10.0,NaN,NaN,USA

In [17]:
text_columns = ["Name", "Gender", "City", "email", "Phone_number", "Country"]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

In [18]:
df["Gender"].value_counts(dropna=False)

Gender
<NA>      2455
Male      1325
female    1270
F         1262
M         1249
male      1226
Female    1213
Name: count, dtype: int64[pyarrow]

In [19]:
df["Gender"] = df["Gender"].str.lower().str.strip()

df["Gender"].value_counts(dropna=False)

Gender
male      2551
female    2483
<NA>      2455
f         1262
m         1249
Name: count, dtype: int64[pyarrow]

In [20]:
numeric_columns = ["Age", "purchase_amount", "feedback_score"]

In [21]:
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [22]:
df[numeric_columns].info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              7424 non-null   float64
 1   purchase_amount  4967 non-null   float64
 2   feedback_score   7538 non-null   float64
dtypes: float64(3)
memory usage: 234.5 KB

In [23]:

df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce")
df["Last_purchase_date"] = pd.to_datetime(df["Last_purchase_date"], errors="coerce")

C:\Users\haroo\AppData\Local\Temp\ipykernel_24436\3240383749.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce")
C:\Users\haroo\AppData\Local\Temp\ipykernel_24436\3240383749.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Last_purchase_date"] = pd.to_datetime(df["Last_purchase_date"], errors="coerce")

In [24]:
df["Signup_Date"] = pd.to_datetime(df["Signup_Date"], errors="coerce", dayfirst=True)
df["Last_purchase_date"] = pd.to_datetime(df["Last_purchase_date"], errors="coerce", dayfirst=True)

In [25]:
print(df[["Signup_Date", "Last_purchase_date"]].head())\

_IncompleteInputError: incomplete input (3272226549.py, line 1)

In [26]:
print(df[["Signup_Date", "Last_purchase_date"]].head())

  Signup_Date Last_purchase_date
0  2024-12-31         2025-08-13
1         NaT                NaT
2         NaT         2023-06-20
3         NaT         2025-09-13
4  2025-07-09                NaT

In [27]:
print(df[["Signup_Date", "Last_purchase_date"]].isnull().sum())

Signup_Date           5004
Last_purchase_date    6652
dtype: int64

In [28]:
print(df[["Signup_Date", "Last_purchase_date"]].info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Signup_Date         4996 non-null   datetime64[us]
 1   Last_purchase_date  3348 non-null   datetime64[us]
dtypes: datetime64[us](2)
memory usage: 156.4 KB
None

In [29]:
print("Signup Date Range:")
print(df["Signup_Date"].min())
print(df["Signup_Date"].max())

print("\nLast Purchase Date Range:")
print(df["Last_purchase_date"].min())
print(df["Last_purchase_date"].max())

Signup Date Range:
2020-08-06 00:00:00
2026-01-26 00:00:00

Last Purchase Date Range:
2020-08-06 00:00:00
2026-01-25 00:00:00

In [30]:
print(df[["Signup_Date", "Last_purchase_date"]].sample(10))

     Signup_Date Last_purchase_date
2190  2025-09-29                NaT
7878         NaT                NaT
789   2021-07-07                NaT
9269  2021-09-04                NaT
3319  2023-06-02                NaT
9107         NaT                NaT
8220         NaT                NaT
8781  2025-07-17         2021-03-04
7949  2025-01-31                NaT
6677  2021-04-01         2021-05-21

In [31]:
invalid_dates = df[
    (df["Signup_Date"].notna()) &
    (df["Last_purchase_date"].notna()) &
    (df["Last_purchase_date"] < df["Signup_Date"])
]

print("Invalid date rows:", len(invalid_dates))
print(invalid_dates[["Signup_Date", "Last_purchase_date"]].head(20))

Invalid date rows: 829
    Signup_Date Last_purchase_date
11   2025-05-29         2021-03-20
13   2024-12-15         2022-03-26
25   2025-07-17         2020-09-05
26   2024-05-28         2020-11-14
32   2025-11-30         2024-01-23
33   2023-04-16         2023-04-06
70   2023-11-23         2023-06-09
73   2023-09-22         2023-05-18
95   2023-02-03         2020-10-12
101  2023-09-15         2022-05-10
103  2023-09-09         2022-05-22
133  2025-11-02         2024-07-19
137  2021-06-22         2020-12-01
138  2024-07-23         2021-01-12
159  2021-03-27         2020-10-12
190  2024-05-20         2023-09-08
207  2023-02-16         2021-11-30
218  2021-08-04         2021-01-14
224  2025-03-03         2023-12-12
227  2024-10-07         2024-06-14

In [32]:
df.loc[
    (df["Signup_Date"].notna()) &
    (df["Last_purchase_date"].notna()) &
    (df["Last_purchase_date"] < df["Signup_Date"]),
    "Last_purchase_date"
] = pd.NaT

In [33]:
print(df["Last_purchase_date"].isnull().sum())

7481

In [34]:
invalid_dates = df[
    (df["Signup_Date"].notna()) &
    (df["Last_purchase_date"].notna()) &
    (df["Last_purchase_date"] < df["Signup_Date"])
]

print("Invalid date rows:", len(invalid_dates))

Invalid date rows: 0

In [35]:
print(df[df["Signup_Date"].isna()][
    ["CustomerID", "Name", "Signup_Date", "Last_purchase_date"]
].head(10))

   CustomerID    Name Signup_Date Last_purchase_date
1          C2    Ravi         NaT                NaT
2           3    Ravi         NaT         2023-06-20
3          C4   Ankit         NaT         2025-09-13
5          C6    Amit         NaT                NaT
6           7   Kiran         NaT                NaT
7           8   Rahul         NaT         2021-11-15
8          C9  Simran         NaT                NaT
10        NaN   Ankit         NaT                NaT
12         13   Rahul         NaT                NaT
15        NaN    <NA>         NaT                NaT

In [36]:
print("Completely empty rows:", df.isna().all(axis=1).sum())

Completely empty rows: 0

In [37]:
print(
    df[
        df["CustomerID"].isna() &
        df["Name"].isna()
    ][["CustomerID", "Name", "Gender", "Age", "City"]].head(20)
)

    CustomerID  Name  Gender    Age       City
15         NaN  <NA>  female   30.0       Pune
33         NaN  <NA>       m   -5.0    Kolkata
50         NaN  <NA>       f   -5.0    Kolkata
59         NaN  <NA>    male   57.0    Kolkata
61         NaN  <NA>    male    NaN    Kolkata
76         NaN  <NA>    <NA>    NaN  Bangalore
93         NaN  <NA>    male   53.0    Kolkata
126        NaN  <NA>    male  200.0      Delhi
159        NaN  <NA>    <NA>   -5.0     Mumbai
166        NaN  <NA>       m   26.0    Chennai
169        NaN  <NA>  female   -5.0    Chennai
215        NaN  <NA>       m   -5.0  Ahmedabad
223        NaN  <NA>  female   18.0    Kolkata
237        NaN  <NA>    male    NaN       <NA>
238        NaN  <NA>    <NA>    NaN       Pune
256        NaN  <NA>  female  200.0      Delhi
324        NaN  <NA>    male   -5.0       Pune
400        NaN  <NA>       m  200.0      Delhi
401        NaN  <NA>       m    NaN    Kolkata
404        NaN  <NA>  female    NaN  Ahmedabad

In [38]:
print("Missing CustomerID:", df["CustomerID"].isna().sum())
print("Missing Name:", df["Name"].isna().sum())

Missing CustomerID: 2379
Missing Name: 1658

In [39]:
print("Missing both CustomerID and Name:",
      (df["CustomerID"].isna() & df["Name"].isna()).sum())

Missing both CustomerID and Name: 418

In [40]:
print("Missing CustomerID:", df["CustomerID"].isna().sum())
print("Missing Name:", df["Name"].isna().sum())

Missing CustomerID: 2379
Missing Name: 1658

In [41]:
print("Age < 0:", (df["Age"] < 0).sum())
print("Age > 100:", (df["Age"] > 100).sum())
print("Missing Age:", df["Age"].isna().sum())

Age < 0: 2506
Age > 100: 2453
Missing Age: 2576

In [42]:
df.loc[(df["Age"] < 0) | (df["Age"] > 100), "Age"] = pd.NA

In [43]:
print("Invalid ages:", ((df["Age"] < 0) | (df["Age"] > 100)).sum())
print("Missing ages:", df["Age"].isna().sum())

Invalid ages: 0
Missing ages: 7535

In [44]:
print(df["Age"].describe())

count    2465.000000
mean       43.698174
std        15.304239
min        18.000000
25%        31.000000
50%        43.000000
75%        58.000000
max        70.000000
Name: Age, dtype: float64

In [45]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [46]:
print("Missing Age:", df["Age"].isna().sum())
print(df["Age"].describe())

Missing Age: 0
count    10000.000000
mean        43.172100
std          7.603161
min         18.000000
25%         43.000000
50%         43.000000
75%         43.000000
max         70.000000
Name: Age, dtype: float64

In [47]:
print(df["Gender"].value_counts(dropna=False))

Gender
male      2551
female    2483
<NA>      2455
f         1262
m         1249
Name: count, dtype: int64[pyarrow]

In [1]:
df["Gender"] = df["Gender"].str.lower().map({
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female"
})

NameError: name 'df' is not defined

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("messy_customer_data.csv")

In [3]:
df.shape

(10000, 12)

In [4]:
df = df.replace(["missing", "not_a_date", ""], np.nan)

In [5]:
df.isnull().sum()

CustomerID            2379
Name                  1658
Gender                2455
Age                   2576
City                  1130
Signup_Date           5004
Last_purchase_date    6652
purchase_amount       5033
feedback_score        2462
email                 5066
Phone_number          2444
Country               1704
dtype: int64

In [6]:
df["Gender"] = df["Gender"].str.lower().map({
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female"
})

In [7]:
print(df["Gender"].value_counts(dropna=False))

Gender
Male      3800
Female    3745
NaN       2455
Name: count, dtype: int64

In [8]:
print(df["Age"].dtype)

float64

In [9]:
print(df["Age"].describe())

count    7424.000000
mean       78.904364
std        87.817619
min        -5.000000
25%        -5.000000
50%        43.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

In [10]:
print(df["Age"].sort_values().head(20))
print(df["Age"].sort_values().tail(20))

6688   -5.0
91     -5.0
88     -5.0
86     -5.0
11     -5.0
6703   -5.0
6700   -5.0
42     -5.0
9996   -5.0
38     -5.0
34     -5.0
33     -5.0
8206   -5.0
29     -5.0
9999   -5.0
8184   -5.0
94     -5.0
4521   -5.0
4518   -5.0
4515   -5.0
Name: Age, dtype: float64
9886   NaN
9902   NaN
9904   NaN
9910   NaN
9916   NaN
9928   NaN
9931   NaN
9932   NaN
9944   NaN
9952   NaN
9955   NaN
9958   NaN
9962   NaN
9963   NaN
9965   NaN
9978   NaN
9979   NaN
9980   NaN
9987   NaN
9991   NaN
Name: Age, dtype: float64

In [11]:
print("Negative ages:", (df["Age"] < 0).sum())

Negative ages: 2506

In [12]:
print(df[df["Age"] > 100]["Age"].value_counts().sort_index())

Age
200.0    2453
Name: count, dtype: int64

In [13]:
print(df[df["Age"] > 100]["Age"].value_counts().sort_index())

Age
200.0    2453
Name: count, dtype: int64

In [14]:
print(df["Age"].value_counts(dropna=False).sort_index().head(30))

Age
-5.0     2506
 18.0      52
 19.0      43
 20.0      45
 21.0      32
 22.0      56
 23.0      42
 24.0      51
 25.0      50
 26.0      43
 27.0      55
 28.0      51
 29.0      51
 30.0      43
 31.0      48
 32.0      44
 33.0      55
 34.0      39
 35.0      47
 36.0      45
 37.0      54
 38.0      67
 39.0      48
 40.0      49
 41.0      48
 42.0      43
 43.0      55
 44.0      57
 45.0      49
 46.0      35
Name: count, dtype: int64

In [15]:
df["Age"] = df["Age"].replace(-5, np.nan)

In [16]:
print(df["Age"].isna().sum())

5082

In [17]:
print(df["Age"].describe())

count    4918.000000
mean      121.658398
std        78.905911
min        18.000000
25%        43.000000
50%        70.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

In [18]:
print(df["Age"].sort_values().head(20))
print(df["Age"].sort_values().tail(20))

9954    18.0
191     18.0
9251    18.0
3703    18.0
1854    18.0
8141    18.0
1234    18.0
8908    18.0
223     18.0
7985    18.0
2928    18.0
9749    18.0
6430    18.0
3768    18.0
1456    18.0
5924    18.0
2786    18.0
6047    18.0
5507    18.0
3437    18.0
Name: Age, dtype: float64
9955   NaN
9958   NaN
9959   NaN
9961   NaN
9962   NaN
9963   NaN
9965   NaN
9968   NaN
9972   NaN
9973   NaN
9974   NaN
9978   NaN
9979   NaN
9980   NaN
9981   NaN
9985   NaN
9987   NaN
9991   NaN
9996   NaN
9999   NaN
Name: Age, dtype: float64

In [19]:
print(df["Age"].describe())

count    4918.000000
mean      121.658398
std        78.905911
min        18.000000
25%        43.000000
50%        70.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

In [20]:
print("Age = 200:", (df["Age"] == 200).sum())

Age = 200: 2453

In [21]:
print(df["Age"].value_counts().sort_index().tail(20))

Age
52.0       40
53.0       36
54.0       40
55.0       32
56.0       41
57.0       37
58.0       53
59.0       60
60.0       44
61.0       46
62.0       39
63.0       35
64.0       60
65.0       43
66.0       37
67.0       49
68.0       49
69.0       61
70.0       41
200.0    2453
Name: count, dtype: int64

In [22]:
print(df["Age"].value_counts().sort_index())

Age
18.0       52
19.0       43
20.0       45
21.0       32
22.0       56
23.0       42
24.0       51
25.0       50
26.0       43
27.0       55
28.0       51
29.0       51
30.0       43
31.0       48
32.0       44
33.0       55
34.0       39
35.0       47
36.0       45
37.0       54
38.0       67
39.0       48
40.0       49
41.0       48
42.0       43
43.0       55
44.0       57
45.0       49
46.0       35
47.0       51
48.0       38
49.0       50
50.0       45
51.0       41
52.0       40
53.0       36
54.0       40
55.0       32
56.0       41
57.0       37
58.0       53
59.0       60
60.0       44
61.0       46
62.0       39
63.0       35
64.0       60
65.0       43
66.0       37
67.0       49
68.0       49
69.0       61
70.0       41
200.0    2453
Name: count, dtype: int64

In [23]:
df["Age"] = df["Age"].replace(200, np.nan)

In [24]:
print(df["Age"].isna().sum())

7535

In [25]:
print(df["Age"].describe())

count    2465.000000
mean       43.698174
std        15.304239
min        18.000000
25%        31.000000
50%        43.000000
75%        58.000000
max        70.000000
Name: Age, dtype: float64

In [26]:
print(df["City"].value_counts(dropna=False))

City
Hyderabad    1144
Mumbai       1133
Pune         1130
NaN          1130
Bangalore    1120
Chennai      1109
Delhi        1091
Ahmedabad    1087
Kolkata      1056
Name: count, dtype: int64

In [27]:
print(df["City"].dtype)

str

In [28]:
print(df["City"].value_counts(dropna=False))

City
Hyderabad    1144
Mumbai       1133
Pune         1130
NaN          1130
Bangalore    1120
Chennai      1109
Delhi        1091
Ahmedabad    1087
Kolkata      1056
Name: count, dtype: int64

In [29]:
print(df["City"].dtype)

str

In [30]:
df["City"] = df["City"].str.strip().str.title()

In [31]:
print(df["City"].value_counts(dropna=False))

City
Hyderabad    1144
Mumbai       1133
Pune         1130
NaN          1130
Bangalore    1120
Chennai      1109
Delhi        1091
Ahmedabad    1087
Kolkata      1056
Name: count, dtype: int64

In [32]:
print(df["purchase_amount"].value_counts(dropna=False).head(20))

purchase_amount
 NaN        5033
-999.00     2501
 1478.98       2
 2766.36       2
 1492.24       2
 3381.59       2
 2533.10       2
 3293.82       2
 2051.47       2
 4535.38       2
 4334.90       2
 887.49        1
 2712.50       1
 2822.00       1
 509.03        1
 1582.43       1
 938.55        1
 1250.98       1
 4772.57       1
 84.02         1
Name: count, dtype: int64

In [33]:
print(df["purchase_amount"].value_counts(dropna=False).head(20))

purchase_amount
 NaN        5033
-999.00     2501
 1478.98       2
 2766.36       2
 1492.24       2
 3381.59       2
 2533.10       2
 3293.82       2
 2051.47       2
 4535.38       2
 4334.90       2
 887.49        1
 2712.50       1
 2822.00       1
 509.03        1
 1582.43       1
 938.55        1
 1250.98       1
 4772.57       1
 84.02         1
Name: count, dtype: int64

In [34]:
print(df["purchase_amount"].dtype)

float64

In [35]:
df["purchase_amount"] = df["purchase_amount"].replace(-999, np.nan)

In [36]:
print(df["purchase_amount"].isnull().sum())

7534

In [37]:
print(df["purchase_amount"].describe())

count    2466.000000
mean     2450.615758
std      1442.834603
min        10.310000
25%      1159.385000
50%      2460.355000
75%      3733.880000
max      4998.670000
Name: purchase_amount, dtype: float64

In [38]:
print(df["feedback_score"].value_counts(dropna=False).sort_index())

feedback_score
-1.0     2489
 1.0      532
 2.0      495
 3.0      556
 4.0      423
 5.0      522
 10.0    2521
 NaN     2462
Name: count, dtype: int64

In [39]:
print(df["feedback_score"].dtype)

float64

In [40]:
df["feedback_score"] = df["feedback_score"].replace([-1, 10], np.nan)

In [41]:
print(df["feedback_score"].value_counts(dropna=False).sort_index())

feedback_score
1.0     532
2.0     495
3.0     556
4.0     423
5.0     522
NaN    7472
Name: count, dtype: int64

In [42]:
print(df["Signup_Date"].value_counts(dropna=False).head(20))

Signup_Date
NaN           5004
07/12/2022      10
14/01/2021       9
28/05/2024       8
22/06/2021       8
15/03/2024       8
10/04/2023       8
07/05/2025       8
10/11/2020       8
31/07/2024       8
25/07/2023       8
28/03/2022       8
17/07/2025       7
27/09/2024       7
23/02/2025       7
11/07/2022       7
06/10/2020       7
03/11/2025       7
09/08/2024       7
20/12/2020       7
Name: count, dtype: int64

In [43]:
print(df["Signup_Date"].dtype)

str

In [44]:
df["Signup_Date"] = pd.to_datetime(
    df["Signup_Date"],
    format="%d/%m/%Y",
    errors="coerce"
)

In [45]:
print(df["Signup_Date"].dtype)

datetime64[us]

In [46]:
print("Missing Signup Dates:", df["Signup_Date"].isna().sum())

Missing Signup Dates: 5004

In [47]:
print("Earliest Signup Date:", df["Signup_Date"].min())
print("Latest Signup Date:", df["Signup_Date"].max())

Earliest Signup Date: 2020-08-06 00:00:00
Latest Signup Date: 2026-01-26 00:00:00

In [48]:
print(df["Last_purchase_date"].value_counts(dropna=False).head(20))

Last_purchase_date
NaN           6652
12/12/2023       7
06/08/2020       7
19/03/2025       7
26/12/2022       6
29/10/2022       6
03/04/2021       6
01/04/2021       6
13/08/2025       5
13/09/2025       5
10/10/2021       5
12/10/2020       5
04/01/2025       5
09/02/2024       5
26/03/2024       5
06/12/2023       5
13/04/2023       5
22/06/2025       5
14/01/2021       5
11/08/2024       5
Name: count, dtype: int64

In [49]:
print(df["Last_purchase_date"].dtype)

str

In [50]:
df["Last_purchase_date"] = pd.to_datetime(
    df["Last_purchase_date"],
    format="%d/%m/%Y",
    errors="coerce"
)

In [51]:
print(df["Last_purchase_date"].dtype)

datetime64[us]

In [52]:
print("Missing Last Purchase Dates:", df["Last_purchase_date"].isna().sum())

Missing Last Purchase Dates: 6652

In [53]:
print("Earliest Last Purchase:", df["Last_purchase_date"].min())
print("Latest Last Purchase:", df["Last_purchase_date"].max())

Earliest Last Purchase: 2020-08-06 00:00:00
Latest Last Purchase: 2026-01-25 00:00:00

In [54]:
invalid_dates = (
    df["Last_purchase_date"].notna()
    & df["Signup_Date"].notna()
    & (df["Last_purchase_date"] < df["Signup_Date"])
)

print("Purchase before signup:", invalid_dates.sum())

Purchase before signup: 829

In [55]:
df.loc[invalid_dates, "Last_purchase_date"] = pd.NaT

In [56]:
print("Missing Last Purchase Dates:", df["Last_purchase_date"].isna().sum())

Missing Last Purchase Dates: 7481

In [57]:
print(df["email"].value_counts(dropna=False).head(20))

email
NaN                5066
user1mail.com         1
user2@mail.com        1
user4mail.com         1
user6mail.com         1
user7@mail.com        1
user9mail.com         1
user10mail.com        1
user12@mail.com       1
user15mail.com        1
user17mail.com        1
user18mail.com        1
user21@mail.com       1
user23mail.com        1
user26mail.com        1
user27mail.com        1
user28@mail.com       1
user30mail.com        1
user32mail.com        1
user36@mail.com       1
Name: count, dtype: int64

In [58]:
print(df["email"].dtype)

str

In [59]:
invalid_email = (
    df["email"].notna()
    & ~df["email"].str.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", na=False)
)

print("Invalid emails:", invalid_email.sum())

Invalid emails: 2422

In [60]:
print(df.loc[invalid_email, "email"].head(20).to_list())

['user1mail.com', 'user4mail.com', 'user6mail.com', 'user9mail.com', 'user10mail.com', 'user15mail.com', 'user17mail.com', 'user18mail.com', 'user23mail.com', 'user26mail.com', 'user27mail.com', 'user30mail.com', 'user32mail.com', 'user37mail.com', 'user42mail.com', 'user45mail.com', 'user58mail.com', 'user64mail.com', 'user71mail.com', 'user77mail.com']

In [61]:
df.loc[invalid_email, "email"] = np.nan

In [62]:
print("Missing/Invalid emails:", df["email"].isna().sum())

Missing/Invalid emails: 7488

In [63]:
print(df["Phone_number"].value_counts(dropna=False).head(20))

Phone_number
abc123        2586
0             2460
NaN           2444
9316267914       1
9234603292       1
9610475090       1
9533545457       1
9720985722       1
9164267579       1
9693394106       1
9919454989       1
9281075045       1
9168733414       1
9948909030       1
9125908338       1
9821999811       1
9246223934       1
9208493774       1
9677889075       1
9450576722       1
Name: count, dtype: int64

In [64]:
print(df["Phone_number"].dtype)

str

In [65]:
df["Phone_number"] = df["Phone_number"].replace(["abc123", "0"], np.nan)

In [66]:
print("Missing Phone Numbers:", df["Phone_number"].isna().sum())

Missing Phone Numbers: 7490

In [67]:
print(df["Phone_number"].dropna().str.len().value_counts().sort_index())

Phone_number
10    2510
Name: count, dtype: int64

In [68]:
print(df["Country"].value_counts(dropna=False))

Country
NaN          1704
USA          1679
Australia    1660
Canada       1658
UK           1658
India        1641
Name: count, dtype: int64

In [69]:
print(df["Country"].dtype)

str

In [70]:
df["Country"] = df["Country"].str.strip()

In [71]:
print(df["Country"].value_counts(dropna=False))

Country
NaN          1704
USA          1679
Australia    1660
Canada       1658
UK           1658
India        1641
Name: count, dtype: int64

In [72]:
print(df["Name"].value_counts(dropna=False).head(30))

Name
NaN       1658
Rahul      876
Sneha      870
Kiran      868
Ankit      845
Priya      831
Ravi       828
Neha       813
Amit       809
Simran     801
Pooja      801
Name: count, dtype: int64

In [73]:
print("Missing CustomerID:", df["CustomerID"].isna().sum())
print("Duplicate CustomerID:", df["CustomerID"].duplicated().sum())

Missing CustomerID: 2379
Duplicate CustomerID: 2378

In [74]:
print(df["CustomerID"].value_counts(dropna=False).head(20))

CustomerID
NaN    2379
C2        1
3         1
C4        1
5         1
C6        1
7         1
8         1
C9        1
10        1
C12       1
13        1
14        1
15        1
17        1
18        1
19        1
20        1
C21       1
C22       1
Name: count, dtype: int64

In [75]:
print("Duplicate valid CustomerID:", df.loc[df["CustomerID"].notna(), "CustomerID"].duplicated().sum())

Duplicate valid CustomerID: 0

In [76]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 15

In [77]:
df = df.drop_duplicates()

In [78]:
print("Duplicate rows:", df.duplicated().sum())
print("Shape:", df.shape)

Duplicate rows: 0
Shape: (9985, 12)

In [79]:
print(df.dtypes)

CustomerID                       str
Name                             str
Gender                           str
Age                          float64
City                             str
Signup_Date           datetime64[us]
Last_purchase_date    datetime64[us]
purchase_amount              float64
feedback_score               float64
email                            str
Phone_number                     str
Country                          str
dtype: object

In [80]:
print(df.isna().sum())

CustomerID            2364
Name                  1656
Gender                2452
Age                   7520
City                  1129
Signup_Date           4989
Last_purchase_date    7466
purchase_amount       7519
feedback_score        7458
email                 7473
Phone_number          7475
Country               1702
dtype: int64

In [81]:
missing_percent = (df.isna().sum() / len(df)) * 100

print(missing_percent.sort_values(ascending=False))

Age                   75.312969
purchase_amount       75.302954
Phone_number          74.862293
email                 74.842263
Last_purchase_date    74.772158
feedback_score        74.692038
Signup_Date           49.964947
Gender                24.556835
CustomerID            23.675513
Country               17.045568
Name                  16.584877
City                  11.306960
dtype: float64

In [82]:
print(df[["Age", "purchase_amount", "feedback_score"]].describe())

               Age  purchase_amount  feedback_score
count  2465.000000      2466.000000     2527.000000
mean     43.698174      2450.615758        2.963197
std      15.304239      1442.834603        1.425030
min      18.000000        10.310000        1.000000
25%      31.000000      1159.385000        2.000000
50%      43.000000      2460.355000        3.000000
75%      58.000000      3733.880000        4.000000
max      70.000000      4998.670000        5.000000

In [83]:
print("Gender:")
print(df["Gender"].value_counts(dropna=False))

print("\nCity:")
print(df["City"].value_counts(dropna=False))

print("\nCountry:")
print(df["Country"].value_counts(dropna=False))

Gender:
Gender
Male      3797
Female    3736
NaN       2452
Name: count, dtype: int64

City:
City
Hyderabad    1142
Mumbai       1131
Pune         1129
NaN          1129
Bangalore    1118
Chennai      1107
Delhi        1089
Ahmedabad    1085
Kolkata      1055
Name: count, dtype: int64

Country:
Country
NaN          1702
USA          1677
Australia    1657
Canada       1656
UK           1655
India        1638
Name: count, dtype: int64

In [84]:
print("Name:")
print(df["Name"].value_counts(dropna=False))

print("\nEmail examples:")
print(df["email"].dropna().head(10))

print("\nPhone examples:")
print(df["Phone_number"].dropna().head(10))

Name:
Name
NaN       1656
Rahul      875
Sneha      869
Kiran      868
Ankit      842
Priya      830
Ravi       825
Neha       813
Amit       807
Pooja      801
Simran     799
Name: count, dtype: int64

Email examples:
2      user2@mail.com
7      user7@mail.com
12    user12@mail.com
21    user21@mail.com
28    user28@mail.com
36    user36@mail.com
41    user41@mail.com
48    user48@mail.com
52    user52@mail.com
62    user62@mail.com
Name: email, dtype: str

Phone examples:
3     9316267914
4     9234603292
14    9610475090
19    9533545457
20    9720985722
21    9164267579
27    9693394106
30    9919454989
33    9281075045
36    9168733414
Name: Phone_number, dtype: str

In [85]:
print("===== FINAL QUALITY CHECK =====")

print("\nShape:")
print(df.shape)

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDuplicate valid CustomerIDs:")
print(df.loc[df["CustomerID"].notna(), "CustomerID"].duplicated().sum())

print("\nMissing values:")
print(df.isna().sum())

print("\nData types:")
print(df.dtypes)

===== FINAL QUALITY CHECK =====

Shape:
(9985, 12)

Duplicate rows:
0

Duplicate valid CustomerIDs:
0

Missing values:
CustomerID            2364
Name                  1656
Gender                2452
Age                   7520
City                  1129
Signup_Date           4989
Last_purchase_date    7466
purchase_amount       7519
feedback_score        7458
email                 7473
Phone_number          7475
Country               1702
dtype: int64

Data types:
CustomerID                       str
Name                             str
Gender                           str
Age                          float64
City                             str
Signup_Date           datetime64[us]
Last_purchase_date    datetime64[us]
purchase_amount              float64
feedback_score               float64
email                            str
Phone_number                     str
Country                          str
dtype: object

In [86]:
df.to_csv("cleaned_customer_data.csv", index=False)

print("Cleaned dataset saved successfully!")
print("File:", "cleaned_customer_data.csv")
print("Shape:", df.shape)

Cleaned dataset saved successfully!
File: cleaned_customer_data.csv
Shape: (9985, 12)

In [87]:
print(df.shape)
print(df.head())
print(df.describe())

(9985, 12)
  CustomerID   Name  Gender   Age       City Signup_Date Last_purchase_date  \
0        NaN  Ankit  Female  36.0     Mumbai  2024-12-31         2025-08-13
1         C2   Ravi  Female   NaN    Kolkata         NaT                NaT
2          3   Ravi  Female  66.0  Ahmedabad         NaT         2023-06-20
3         C4  Ankit    Male  44.0    Kolkata         NaT         2025-09-13
4          5  Rahul    Male   NaN  Ahmedabad  2025-07-09                NaT

   purchase_amount  feedback_score           email Phone_number Country
0              NaN             2.0             NaN          NaN  Canada
1              NaN             NaN             NaN          NaN  Canada
2              NaN             NaN  user2@mail.com          NaN   India
3              NaN             NaN             NaN   9316267914     USA
4              NaN             NaN             NaN   9234603292     USA
               Age                 Signup_Date          Last_purchase_date  \
count  2465.000000                        4996                        2519
mean     43.698174  2023-05-03 09:00:43.234587  2023-08-21 23:10:15.958713
min      18.000000         2020-08-06 00:00:00         2020-08-06 00:00:00
25%      31.000000         2021-12-20 18:00:00         2022-05-26 00:00:00
50%      43.000000         2023-05-02 12:00:00         2023-10-03 00:00:00
75%      58.000000         2024-09-13 00:00:00         2025-01-04 12:00:00
max      70.000000         2026-01-26 00:00:00         2026-01-25 00:00:00
std      15.304239                         NaN                         NaN

       purchase_amount  feedback_score
count      2466.000000     2527.000000
mean       2450.615758        2.963197
min          10.310000        1.000000
25%        1159.385000        2.000000
50%        2460.355000        3.000000
75%        3733.880000        4.000000
max        4998.670000        5.000000
std        1442.834603        1.425030